name: Build & Publish Frontend to GHCR

on:
  push:
    branches: ["main", "develop", "integration/**", "ci/build-publish-and-nginx-proxy"] 
  workflow_call:
    outputs:
      image:
        description: Image reference pushed
        value: ${{ jobs.publish.outputs.image }}
      digest:
        description: Image digest
        value: ${{ jobs.publish.outputs.digest }}
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/apesensei/nightbff-frontend
          tags: |
            type=sha,format=short,prefix=int-

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: true
          sbom: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: v2.2.4

      - name: Sign image (keyless)
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build.outputs.digest }}
        run: cosign sign --yes "${TAGS}@${DIGEST}"

      - name: Pull image to local daemon (by digest)
        run: docker pull ghcr.io/apesensei/nightbff-frontend@${{ steps.build.outputs.digest }}

      - name: Generate SBOM (authenticated, by digest)
        env:
          SYFT_REGISTRY_AUTH_USERNAME: ${{ github.actor }}
          SYFT_REGISTRY_AUTH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm \
            -e SYFT_REGISTRY_AUTH_USERNAME \
            -e SYFT_REGISTRY_AUTH_PASSWORD \
            -v /var/run/docker.sock:/var/run/docker.sock \
            anchore/syft:latest \
            docker:ghcr.io/apesensei/nightbff-frontend@${{ steps.build.outputs.digest }} \
            -o spdx-json > sbom.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.sha }}
          path: sbom.spdx.json
